process.env.NODE_ENV ??= 'test'
process.env.PORT ??= '3333'
process.env.HOST ??= '127.0.0.1'
process.env.DATABASE_URL ??= 'mysql://agendei:agendei@localhost:3306/agendei'
process.env.JWT_SECRET ??= 'test-secret-with-at-least-32-characters'
process.env.JWT_EXPIRES_IN ??= '1h'
